language: java
matrix:
  include:
  - os: linux
    sudo: false
    jdk: oraclejdk8
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
env:
  global:
  - REAL_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod -R ug+x .travis
script:
- chmod -R ug+x .travis
- ".travis/build.sh"
before_deploy: bash .travis/deploy.sh $REAL_BRANCH $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: pXlrDYfT8BN7gvemPzLVB/09iCSdW3q4i7qj5lk9UnF8uy5j1Cd2kjDJRBbYMKaik1GLoPS2ekaFkCkaTs9149kc8zdDG9vHoETrmsMvZkj6n2EMyaQukBCLMfsBXCPwEHsDiu0bg/Wa74umcgVvejVL62Zi1DB2FNxrA+oi90biy4/RN+UymLRkLkZMLHqrcZ/vbEH4tQldiC7LMsvZ5S03zxxhuXGwRahyiFr/9lSN8FZkCZLF2AivgLkiCFCshtrb95YZEtG4E4KOGlRrKqWrtChBBv09thVvanwGN6XEcxkqFIZIEhfRZTpvQNYf3Ax76TAcsaX5i4id++1UmE0dc1+LP8kbS9Mll7TfgRgGvs0xlnCLAoR4qYFnwxTzLERYNJZgmWD15qUt0vp8VdFkEfCjxDTkp8jUVDjykcdY9cnIVbVeMxLvlsskjqf3I9uXVct4RWRVelEV5d/ubbAZOEPm4DqrCuAGNr8zwJedq6BuqW74HSqykxTAXp6sb6l3cNzkZ0MG/iHW7hSsvQrDLVaHP7dE2WPUyVbeEfql91+fxCWxvDL0waPHXFQ2lhIqAtXIp2ZvdV1l5Co9LifqILYNF9ftmT6GGNfJQW5dsBFnXwsuIF75sOtJn5Omf0iTzOKwI6I7bKnHL9G+qwuXBqrXudpxfdODOWpfPjE=
  file:
    - build/libs/LGP-lib-$TRAVIS_TAG-$(date +%Y-%m-%d).jar
  skip_cleanup: true
  overwrite: true
  on:
    repo: JedS6391/LGP-lib
    all_branches: true
    condition: "$REAL_BRANCH =~ ^release.*$"
    tags: true
